#pragma once
#include <array>

// Shared by the overlay title and release comparison; not the upstream engine version.
#define OPTISHADE_VERSION_MAJOR 0
#define OPTISHADE_VERSION_MINOR 20
#define OPTISHADE_VERSION_PATCH 9
#define OPTISHADE_STRINGIFY_IMPL(x) #x
#define OPTISHADE_STRINGIFY(x) OPTISHADE_STRINGIFY_IMPL(x)
#define OPTISHADE_VERSION_TEXT OPTISHADE_STRINGIFY(OPTISHADE_VERSION_MAJOR) "." OPTISHADE_STRINGIFY(OPTISHADE_VERSION_MINOR) "." OPTISHADE_STRINGIFY(OPTISHADE_VERSION_PATCH)
namespace OptiShadeVersion {
inline constexpr std::array<int, 3> Current{OPTISHADE_VERSION_MAJOR, OPTISHADE_VERSION_MINOR, OPTISHADE_VERSION_PATCH};
}
